name: storeangelApp
description: A new Flutter application.

version: 1.0.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^0.1.2
  get_it: ^4.0.4
  provider: ^4.3.2+1
  connectivity: ^0.4.9
  shared_preferences: ^0.5.8
  fluttertoast: ^7.0.2
  intl: ^0.16.1
  image_picker: ^0.6.7+4
  flutter_rating_bar: ^1.1.0
  easy_localization: ^2.3.3
  google_maps_flutter: ^0.5.30
  location: ^3.0.2
  smooth_page_indicator: ^0.2.0
  dots_indicator: ^1.2.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.0
  flare_splash_screen: ^3.0.1
  geocoder: ^0.2.1
  cached_network_image: ^2.2.0+1
  flutter_slidable: ^0.5.5
  jiffy: ^3.0.1
  carousel_slider: ^2.2.1
  percent_indicator: ^2.1.5
  flutter_statusbarcolor: ^0.2.3
  flutter_datetime_picker: ^1.4.0
  circular_check_box: ^1.0.2
  timeago: ^2.0.26
  google_sign_in: ^4.5.1
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.1
  flutter_statusbar_manager: ^2.0.0

  #https://pub.dev/packages/flutter_svg/install
  flutter_svg: ^0.19.1

  #https://pub.dev/packages/assorted_layout_widgets/install
  flutter_webview_plugin: ^0.3.11
  sign_in_with_apple: ^2.5.4
  http_auth: ^0.3.0
#  webview_flutter: ^0.3.22+1
  webview_flutter_plus: ^0.1.1+9
  flutter_pay: ^0.9.1
  mollie: ^0.8.2
  #stripe_payment: ^1.0.7
  photo_manager: ^0.5.8
  path_provider: ^1.6.14
  flutter_better_camera: ^0.6.1
  file_picker: ^2.0.0
  sliver_tools: ^0.1.5
  apple_sign_in: ^0.1.0
#  flutter_group_sliver: ^0.0.2
  calendar_timeline: ^0.6.3
  photo_view: ^0.10.2






  flutter_group_sliver:
    git: https://github.com/htbProgramming/flutter_group_sliver.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sample_images/
    - assets/animation/
    - assets/translations/
    - assets/
    - assets/images/sample_images/
    - assets/images/couirer_candidates/
    - assets/images/illustration/
    - assets/images/svg/
    - assets/map_styles/

  fonts:
     - family: StoreangelIcons
       fonts:
          - asset: fonts/StoreangelIcons.ttf
     - family: StoreAngelIcon2
       fonts:
          - asset: fonts/StoreAngel.ttf

     - family: SFUIText
       fonts:
          - asset: fonts/SFUIText-Regular.ttf
          - asset: fonts/SFUIText-Bold.ttf
          - asset: fonts/SFUIText-Medium.ttf
     - family: Roboto
       fonts:
             - asset: fonts/Roboto/Roboto-Regular.ttf
             - asset: fonts/Roboto/Roboto-Bold.ttf
             - asset: fonts/Roboto/Roboto-Medium.ttf
             - asset: fonts/Roboto/Roboto-Light.ttf
     - family: PTMono
       fonts:
          - asset: fonts/PTMono-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
