/// Flutter icons StoreangelIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StoreangelIcons
///      fonts:
///       - asset: fonts/StoreangelIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StoreangelIcons {
  StoreangelIcons._();

  static const _kFontFam = 'StoreangelIcons';
  static const _kFontFam2='StoreAngelIcon2';
  static const _kFontPkg = null;

  static const IconData addresses_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrival_location_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_direction_down = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_forward_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill_outlined_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_information_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_clock_full = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_clock = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_full = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancle_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancle_simple_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_on_payment_full_icon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_on_payment_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cashier_full = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cashier = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_to_courier_profile_full = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_mark_full = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_to_courier_profile_screen = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_mark_outlined = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_simple_icon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compact_camera_full = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compact_camera = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_order_flow_icon_full = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_order_flow_icon = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_icon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData details_courier_tab_full = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData details_courier_tab = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_full = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_icon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_icon = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_bag_outlined = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_images_outlined_icon = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_full = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined_icon = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_tab_full = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_tab = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_full = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass1 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card_full = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurance_icon = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pin_full = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pin = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_full = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_icon = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_icon = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer_courier_tab_full = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer_courier_tab = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_courier_tab_full = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_courier_tab = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_icon = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_icon = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outlined_icon = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal_information_icon = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photos_full = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photos_icon = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photos = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_consumer_tab_full = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_consumer_tab = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_courier_tab_full = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_courier_tab = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_full = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select_product = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_message_icon = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_icon = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_icon = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_with_three_dots_icon = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket_full = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_card_order_icon = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart_order_full = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storeangel_flying_baby_icon = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stores_tab_full = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stores_tab = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy_full = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_icon = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watchlist_tab_full = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watchlist_tab = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selectproduct = IconData(0xe801, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData grocery_list = IconData(0xe801, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe802, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe803, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData sortUp = IconData(0xe804, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData send_message = IconData(0xe806, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData smiley = IconData(0xe807, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData thumbsUp = IconData(0xe808, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe809, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80a, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData banana_apple_full = IconData(0xe80b, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData banana_apple = IconData(0xe80c, fontFamily: _kFontFam2,fontPackage: _kFontPkg);




}
